### ISSUE TITLE
About PD-GAN

### ISSUE THREAD

**Issue by TenChickens666** [houliangict/adcgan#1]
Hi, I just want to make sure how you deal with PD-GAN in your paper, because I can not find anything about PD-GAN in this version of codes. I think it is a good project and it helps me a lot. Thank you so much!

**Comment by liang-hou** [comment]
Thank you for your recognition and kind words about our work. PDGAN will be run when you enter `--loss pdgan` in the command. You can refer to the script `launch_cifar10_ema_pdgan.sh` for example. This is because I set `projection=True` for the discriminator if the `loss` contains `pd` (see Line 45 in `train.py`), which will activate the computational pipeline of PDGAN (see Lines 317 and 413 in `BigGAN.py`).
